import React, { useState, useEffect, useContext, useRef } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { AuthContext } from '../context/AuthContext';
import api from '../utils/axios';
import { motion, AnimatePresence } from 'framer-motion';
import toast from 'react-hot-toast';
import { FaArrowLeft, FaArrowRight, FaSave, FaEye, FaRocket, FaMagic } from 'react-icons/fa';

const steps = ['Basic Info', 'Date & Time', 'Venue', 'Tickets', 'Organizer', 'Media', 'Preview'];

const CreateEvent = () => {
    const { user } = useContext(AuthContext);
    const navigate = useNavigate();
    const { id } = useParams();
    const [step, setStep] = useState(0);
    const [loading, setLoading] = useState(false);
    const [aiLoading, setAiLoading] = useState(false);

    const [form, setForm] = useState({
        title: '', subtitle: '', description: '', category: '', eventType: 'in-person', tags: [],
        date: '', startTime: '', endTime: '', registrationStart: '', registrationEnd: '',
        location: '', venue: { name: '', address: '', city: '', state: '', country: '', pincode: '' },
        ticketPrice: 0, upiId: '', totalSeats: 100, maxTicketsPerUser: 1,
        organizer: { name: user?.name || '', email: user?.email || '', phone: '', website: '' },
        banner: '', thumbnail: '', gallery: [], highlights: [], status: 'published'
    });

    useEffect(() => {
        if (id) {
            api.get(`/events/${id}`).then(({ data }) => {
                setForm({
                    title: data.title || '',
                    subtitle: data.subtitle || '',
                    description: data.description || '',
                    category: data.category || '',
                    eventType: data.eventType || 'in-person',
                    tags: data.tags || [],
                    date: data.date ? new Date(data.date).toISOString().substring(0, 10) : '',
                    startTime: data.startTime || '',
                    endTime: data.endTime || '',
                    registrationStart: data.registrationStart ? new Date(data.registrationStart).toISOString().substring(0, 10) : '',
                    registrationEnd: data.registrationEnd ? new Date(data.registrationEnd).toISOString().substring(0, 10) : '',
                    location: data.location || '',
                    venue: data.venue || { name: '', address: '', city: '', state: '', country: '', pincode: '' },
                    ticketPrice: data.ticketPrice || 0,
                    upiId: data.upiId || '',
                    totalSeats: data.totalSeats || 100,
                    maxTicketsPerUser: data.maxTicketsPerUser || 1,
                    organizer: data.organizer || { name: user?.name || '', email: user?.email || '', phone: '', website: '' },
                    banner: data.banner || data.image || '',
                    thumbnail: data.thumbnail || '',
                    gallery: data.gallery || [],
                    highlights: data.highlights || [],
                    status: data.status || 'published'
                });
            }).catch(() => toast.error('Failed to load event details'));
        }
    }, [id, user]);

    const [tagInput, setTagInput] = useState('');
    const lastAutoGenTitle = useRef('');

    // Auto-generate description when title field loses focus
    const autoGenerateDescription = async () => {
        const title = form.title.trim();
        // Only auto-generate if: title has 3+ chars, description is empty, and we haven't already generated for this title
        if (title.length >= 3 && !form.description.trim() && lastAutoGenTitle.current !== title && !id) {
            lastAutoGenTitle.current = title;
            setAiLoading(true);
            try {
                const { data } = await api.post('/gemini/generate-description', {
                    title, category: form.category || 'General', eventType: form.eventType || 'in-person'
                });
                if (data.description) {
                    updateForm('description', data.description);
                    toast.success('✨ Description auto-generated from title!');
                }
            } catch (err) {
                console.warn('Auto-generate description failed:', err.message);
            } finally {
                setAiLoading(false);
            }
        }
    };

    const updateForm = (field, value) => setForm(prev => ({ ...prev, [field]: value }));
    const updateNested = (parent, field, value) => setForm(prev => ({ ...prev, [parent]: { ...prev[parent], [field]: value } }));

    const addTag = () => {
        if (tagInput.trim() && !form.tags.includes(tagInput.trim())) {
            updateForm('tags', [...form.tags, tagInput.trim().toLowerCase()]);
            setTagInput('');
        }
    };

    const removeTag = (tag) => updateForm('tags', form.tags.filter(t => t !== tag));

    const handleImageUpload = async (e, field) => {
        const file = e.target.files[0];
        if (!file) return;
        const formData = new FormData();
        formData.append('image', file);
        formData.append('folder', 'evora/events');
        try {
            toast.loading('Uploading...', { id: 'upload' });
            const { data } = await api.post('/upload', formData, { headers: { 'Content-Type': 'multipart/form-data' } });
            if (field === 'gallery') updateForm('gallery', [...form.gallery, data.url]);
            else updateForm(field, data.url);
            toast.success('Uploaded!', { id: 'upload' });
        } catch { toast.error('Upload failed', { id: 'upload' }); }
    };

    const generateAI = async (type) => {
        if (!form.title || !form.title.trim()) {
            toast.error('Please enter an Event Title first!');
            return;
        }
        setAiLoading(true);
        try {
            const { data } = await api.post(`/gemini/generate-${type}`, {
                title: form.title, description: form.description, category: form.category || 'General', eventType: form.eventType || 'in-person'
            });
            if (type === 'description') updateForm('description', data.description);
            if (type === 'highlights') updateForm('highlights', data.highlights);
            if (type === 'tags') updateForm('tags', [...new Set([...form.tags, ...(data.tags || [])])]);
            toast.success(`${type} generated!`);
        } catch (err) {
            toast.error(err.response?.data?.message || 'AI generation failed');
        } finally {
            setAiLoading(false);
        }
    };

    const handleSubmit = async (status = 'published') => {
        setLoading(true);
        try {
            const payload = { ...form, status, image: form.banner, ticketType: form.ticketPrice > 0 ? 'paid' : 'free' };
            if (id) {
                await api.put(`/events/${id}`, payload);
                toast.success('Event details updated successfully!');
            } else {
                await api.post('/events', payload);
                toast.success(status === 'draft' ? 'Saved as draft!' : 'Event published!');
            }
            navigate(user.role === 'organizer' ? '/organizer' : '/admin');
        } catch (err) { toast.error(err.response?.data?.message || 'Failed to save event'); }
        finally { setLoading(false); }
    };

    const inputClass = "w-full px-4 py-3 rounded-xl border border-gray-200 dark:border-dark-400 dark:bg-dark-600 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-primary-500 transition outline-none";
    const labelClass = "block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2";

    const renderStep = () => {
        switch (step) {
            case 0: return (
                <div className="space-y-5">
                    <div><label className={labelClass}>Title *</label><input className={inputClass} value={form.title} onChange={e => updateForm('title', e.target.value)} onBlur={autoGenerateDescription} placeholder="Event title — description will auto-generate based on this" required /></div>
                    <div><label className={labelClass}>Subtitle</label><input className={inputClass} value={form.subtitle} onChange={e => updateForm('subtitle', e.target.value)} placeholder="Short tagline" /></div>
                    <div>
                        <div className="flex items-center justify-between mb-2"><label className={labelClass + " mb-0"}>Description *</label>
                            <button type="button" onClick={() => generateAI('description')} disabled={aiLoading || !form.title} className="text-xs font-bold text-primary-600 hover:text-primary-700 flex items-center gap-1 disabled:opacity-50"><FaMagic /> {aiLoading ? 'Generating...' : 'AI Generate'}</button>
                        </div>
                        {aiLoading && !form.description ? (
                            <div className={inputClass + " h-36 flex items-center justify-center bg-primary-50/50 dark:bg-primary-950/20 border-primary-200 dark:border-primary-800"}>
                                <div className="flex items-center gap-3 text-primary-600 dark:text-primary-400">
                                    <div className="w-5 h-5 border-2 border-primary-500 border-t-transparent rounded-full animate-spin"></div>
                                    <span className="text-sm font-semibold">✨ AI is writing a description based on "{form.title}"...</span>
                                </div>
                            </div>
                        ) : (
                            <textarea className={inputClass + " h-36"} value={form.description} onChange={e => updateForm('description', e.target.value)} placeholder="Describe your event... (auto-generates when you type a title)" required />
                        )}
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                        <div><label className={labelClass}>Category *</label>
                            <select className={inputClass} value={form.category} onChange={e => updateForm('category', e.target.value)}>
                                <option value="">Select</option>
                                {['Technology', 'Music', 'Business', 'Art', 'Sports', 'Education', 'Health', 'Food', 'Other'].map(c => <option key={c} value={c}>{c}</option>)}
                            </select>
                        </div>
                        <div><label className={labelClass}>Event Type</label>
                            <select className={inputClass} value={form.eventType} onChange={e => updateForm('eventType', e.target.value)}>
                                <option value="in-person">In Person</option><option value="online">Online</option><option value="hybrid">Hybrid</option>
                            </select>
                        </div>
                    </div>
                    <div>
                        <div className="flex items-center justify-between mb-2"><label className={labelClass + " mb-0"}>Tags</label>
                            <button type="button" onClick={() => generateAI('tags')} disabled={aiLoading || !form.title} className="text-xs font-bold text-primary-600 hover:text-primary-700 flex items-center gap-1 disabled:opacity-50"><FaMagic /> AI Suggest</button>
                        </div>
                        <div className="flex gap-2 mb-2"><input className={inputClass} value={tagInput} onChange={e => setTagInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && (e.preventDefault(), addTag())} placeholder="Type & press Enter" />
                            <button type="button" onClick={addTag} className="px-4 py-2 bg-primary-600 text-white rounded-xl text-sm font-bold hover:bg-primary-700 transition shrink-0">Add</button>
                        </div>
                        <div className="flex flex-wrap gap-2">{form.tags.map(t => <span key={t} className="bg-primary-100 dark:bg-primary-900 text-primary-700 dark:text-primary-200 text-xs font-bold px-3 py-1 rounded-full cursor-pointer hover:bg-red-100 hover:text-red-600 transition" onClick={() => removeTag(t)}>{t} ×</span>)}</div>
                    </div>
                </div>
            );
            case 1: return (
                <div className="space-y-5">
                    <div><label className={labelClass}>Event Date *</label><input type="date" className={inputClass} value={form.date} onChange={e => updateForm('date', e.target.value)} required /></div>
                    <div className="grid grid-cols-2 gap-4">
                        <div><label className={labelClass}>Start Time</label><input type="time" className={inputClass} value={form.startTime} onChange={e => updateForm('startTime', e.target.value)} /></div>
                        <div><label className={labelClass}>End Time</label><input type="time" className={inputClass} value={form.endTime} onChange={e => updateForm('endTime', e.target.value)} /></div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                        <div><label className={labelClass}>Registration Start</label><input type="date" className={inputClass} value={form.registrationStart} onChange={e => updateForm('registrationStart', e.target.value)} /></div>
                        <div><label className={labelClass}>Registration End</label><input type="date" className={inputClass} value={form.registrationEnd} onChange={e => updateForm('registrationEnd', e.target.value)} /></div>
                    </div>
                </div>
            );
            case 2: return (
                <div className="space-y-5">
                    <div><label className={labelClass}>Location / Address *</label><input className={inputClass} value={form.location} onChange={e => updateForm('location', e.target.value)} placeholder="Full address" required /></div>
                    <div className="grid grid-cols-2 gap-4">
                        <div><label className={labelClass}>Venue Name</label><input className={inputClass} value={form.venue.name} onChange={e => updateNested('venue', 'name', e.target.value)} placeholder="Venue name" /></div>
                        <div><label className={labelClass}>City</label><input className={inputClass} value={form.venue.city} onChange={e => updateNested('venue', 'city', e.target.value)} placeholder="City" /></div>
                        <div><label className={labelClass}>State</label><input className={inputClass} value={form.venue.state} onChange={e => updateNested('venue', 'state', e.target.value)} placeholder="State" /></div>
                        <div><label className={labelClass}>Country</label><input className={inputClass} value={form.venue.country} onChange={e => updateNested('venue', 'country', e.target.value)} placeholder="Country" /></div>
                        <div><label className={labelClass}>Pincode</label><input className={inputClass} value={form.venue.pincode} onChange={e => updateNested('venue', 'pincode', e.target.value)} placeholder="Pincode" /></div>
                    </div>
                </div>
            );
            case 3: return (
                <div className="space-y-5">
                    <div className="grid grid-cols-2 gap-4">
                        <div><label className={labelClass}>Ticket Price (₹)</label><input type="number" min="0" className={inputClass} value={form.ticketPrice} onChange={e => updateForm('ticketPrice', Number(e.target.value))} /></div>
                        <div><label className={labelClass}>Total Seats *</label><input type="number" min="1" className={inputClass} value={form.totalSeats} onChange={e => updateForm('totalSeats', Number(e.target.value))} required /></div>
                        <div><label className={labelClass}>Max Tickets / User</label><input type="number" min="1" max="10" className={inputClass} value={form.maxTicketsPerUser} onChange={e => updateForm('maxTicketsPerUser', Number(e.target.value))} /></div>
                    </div>
                    {form.ticketPrice > 0 ? (
                        <div className="bg-amber-50 dark:bg-amber-950/40 p-4 rounded-xl border border-amber-200 dark:border-amber-800/50 space-y-2">
                            <label className={labelClass}>Organizer UPI ID (for receiving attendee payments) *</label>
                            <input type="text" className={inputClass} value={form.upiId} onChange={e => updateForm('upiId', e.target.value)} placeholder="e.g. organizer@upi or 9876543210@paytm" />
                            <p className="text-xs text-amber-700 dark:text-amber-300 font-medium">Attendees booking paid tickets will scan a UPI QR code generated with this UPI ID to send payment directly to you.</p>
                        </div>
                    ) : (
                        <div className="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl text-green-700 dark:text-green-400 font-medium text-sm">This is a free event</div>
                    )}
                </div>
            );
            case 4: return (
                <div className="space-y-5">
                    <div className="grid grid-cols-2 gap-4">
                        <div><label className={labelClass}>Organizer Name</label><input className={inputClass} value={form.organizer.name} onChange={e => updateNested('organizer', 'name', e.target.value)} /></div>
                        <div><label className={labelClass}>Email</label><input type="email" className={inputClass} value={form.organizer.email} onChange={e => updateNested('organizer', 'email', e.target.value)} /></div>
                        <div><label className={labelClass}>Phone</label><input className={inputClass} value={form.organizer.phone} onChange={e => updateNested('organizer', 'phone', e.target.value)} /></div>
                        <div><label className={labelClass}>Website</label><input className={inputClass} value={form.organizer.website} onChange={e => updateNested('organizer', 'website', e.target.value)} placeholder="https://" /></div>
                    </div>
                </div>
            );
            case 5: return (
                <div className="space-y-5">
                    <div>
                        <label className={labelClass}>Banner Image</label>
                        <input type="file" accept="image/*" onChange={e => handleImageUpload(e, 'banner')} className="text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-xl file:border-0 file:bg-primary-50 file:text-primary-700 file:font-semibold hover:file:bg-primary-100" />
                        {form.banner && <img src={form.banner} alt="Banner" className="mt-3 h-40 w-full object-cover rounded-xl" />}
                    </div>
                    <div>
                        <label className={labelClass}>Thumbnail</label>
                        <input type="file" accept="image/*" onChange={e => handleImageUpload(e, 'thumbnail')} className="text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-xl file:border-0 file:bg-primary-50 file:text-primary-700 file:font-semibold hover:file:bg-primary-100" />
                        {form.thumbnail && <img src={form.thumbnail} alt="Thumbnail" className="mt-3 h-32 w-32 object-cover rounded-xl" />}
                    </div>
                    <div>
                        <label className={labelClass}>Gallery</label>
                        <input type="file" accept="image/*" onChange={e => handleImageUpload(e, 'gallery')} className="text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-xl file:border-0 file:bg-primary-50 file:text-primary-700 file:font-semibold hover:file:bg-primary-100" />
                        <div className="flex gap-3 mt-3 flex-wrap">{form.gallery.map((g, i) => <img key={i} src={g} alt="" className="h-24 w-24 object-cover rounded-lg" />)}</div>
                    </div>
                    <div>
                        <div className="flex items-center justify-between mb-2"><label className={labelClass + " mb-0"}>Highlights</label>
                            <button type="button" onClick={() => generateAI('highlights')} disabled={aiLoading || !form.title} className="text-xs font-bold text-primary-600 hover:text-primary-700 flex items-center gap-1 disabled:opacity-50"><FaMagic /> AI Generate</button>
                        </div>
                        <div className="space-y-2">{form.highlights.map((h, i) => <div key={i} className="flex items-center gap-2"><span className="text-green-500">✓</span><span className="text-sm text-gray-700 dark:text-gray-300">{h}</span></div>)}</div>
                    </div>
                </div>
            );
            case 6: return (
                <div className="space-y-6">
                    <h3 className="text-2xl font-bold text-gray-900 dark:text-white">{form.title || 'Untitled Event'}</h3>
                    {form.subtitle && <p className="text-lg text-gray-500">{form.subtitle}</p>}
                    {form.banner && <img src={form.banner} alt="Banner" className="w-full h-48 object-cover rounded-xl" />}
                    <div className="grid grid-cols-2 gap-4 text-sm">
                        <div><span className="font-bold text-gray-500">Category:</span> <span className="text-gray-800 dark:text-white">{form.category}</span></div>
                        <div><span className="font-bold text-gray-500">Date:</span> <span className="text-gray-800 dark:text-white">{form.date}</span></div>
                        <div><span className="font-bold text-gray-500">Location:</span> <span className="text-gray-800 dark:text-white">{form.location}</span></div>
                        <div><span className="font-bold text-gray-500">Price:</span> <span className="text-gray-800 dark:text-white">{form.ticketPrice === 0 ? 'Free' : `₹${form.ticketPrice}`}</span></div>
                        <div><span className="font-bold text-gray-500">Seats:</span> <span className="text-gray-800 dark:text-white">{form.totalSeats}</span></div>
                        <div><span className="font-bold text-gray-500">Type:</span> <span className="text-gray-800 dark:text-white">{form.eventType}</span></div>
                    </div>
                    <div><span className="font-bold text-gray-500 text-sm">Description:</span><p className="text-gray-700 dark:text-gray-300 mt-1 text-sm leading-relaxed">{form.description}</p></div>
                    {form.tags.length > 0 && <div className="flex flex-wrap gap-2">{form.tags.map(t => <span key={t} className="bg-gray-100 dark:bg-dark-500 text-gray-700 dark:text-gray-300 text-xs font-medium px-3 py-1 rounded-full">{t}</span>)}</div>}
                </div>
            );
            default: return null;
        }
    };

    return (
        <div className="max-w-3xl mx-auto">
            <div className="mb-8">
                <h1 className="text-3xl font-extrabold text-gray-900 dark:text-white mb-2">Create Event</h1>
                <div className="flex items-center gap-2 overflow-x-auto pb-2">
                    {steps.map((s, i) => (
                        <button key={i} onClick={() => setStep(i)} className={`text-xs font-bold px-3 py-1.5 rounded-full whitespace-nowrap transition ${i === step ? 'bg-primary-600 text-white' : i < step ? 'bg-green-100 text-green-700' : 'bg-gray-100 dark:bg-dark-500 text-gray-500 dark:text-gray-400'}`}>
                            {i < step ? '✓ ' : ''}{s}
                        </button>
                    ))}
                </div>
            </div>

            <motion.div key={step} initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }}
                className="bg-white dark:bg-dark-600 rounded-2xl shadow-sm border border-gray-100 dark:border-dark-400 p-6 sm:p-8 mb-6">
                {renderStep()}
            </motion.div>

            <div className="flex items-center justify-between gap-4">
                <button onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0} className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-gray-600 dark:text-gray-300 bg-gray-100 dark:bg-dark-500 hover:bg-gray-200 transition disabled:opacity-50">
                    <FaArrowLeft /> Back
                </button>
                <div className="flex gap-3">
                    <button onClick={() => handleSubmit('draft')} disabled={loading} className="flex items-center gap-2 px-5 py-3 rounded-xl font-bold text-gray-700 dark:text-gray-200 bg-gray-100 dark:bg-dark-500 hover:bg-gray-200 transition"><FaSave /> Draft</button>
                    {step === steps.length - 1 ? (
                        <button onClick={() => handleSubmit('published')} disabled={loading} className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-white bg-primary-600 hover:bg-primary-700 transition shadow-lg">
                            <FaRocket /> {loading ? 'Publishing...' : 'Publish Event'}
                        </button>
                    ) : (
                        <button onClick={() => setStep(Math.min(steps.length - 1, step + 1))} className="flex items-center gap-2 px-6 py-3 rounded-xl font-bold text-white bg-primary-600 hover:bg-primary-700 transition shadow-lg">
                            Next <FaArrowRight />
                        </button>
                    )}
                </div>
            </div>
        </div>
    );
};

export default CreateEvent;
